In [1]:
import numpy as np

In [2]:
#리스트와 넘파이 차이

list_ = [1,2,3]
print(list_)

[1, 2, 3]


In [3]:
np.array([1,2,3])

# array: 배열
# np.array(리스트)


array([1, 2, 3])

In [8]:
arr = np.array([1,2,3])
print(arr)  # 리스트와 같이 출력됨 (' , ' 없음, 콤마 상실 )
print(arr[0]) # 리스트와 같이 indexing 된다 -->> 순서가 있다는 의미

[1 2 3]
1


In [9]:
# 왜 넘파이를 배울까

# 리스트와 리스트를 더하면 --> 연장된다(크기가 커짐)
[1,2,3] +[4,5,6]


[1, 2, 3, 4, 5, 6]

In [10]:
c = [1,2,3] +[4,5,6]
print(c)
print(len(c))

[1, 2, 3, 4, 5, 6]
6


In [11]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])

arr_a +arr_b  # -> 같은 위치에 있는 원소(elements)끼리 더해진다(연산이 된다는 의미)

array([5, 7, 9])

In [13]:
np.array([[1,2,3],[4,5,6],[7,8,9]])  # 2차원


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr_e = np.array([[1,2,3],[4,5,6],[7,8,9]])  
print(arr_e[-1])
arr_e[-1][-1]

[7 8 9]


9

#### 넘파이 배열 속성

In [20]:
arr_e = np.array([[1,2,3],[4,5,6],[7,8,9]])  
print(arr_e)
#배열의 형상
print(arr_e.shape)
#(3,3): 3행 3열

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [23]:
arr = np.array([1,2,3])
print(arr)
print(arr.shape) #1차원

[1 2 3]
(3,)


In [24]:
arr_f = np.array([[1],[2],[3]])
print(arr_f)
print(arr_f.shape) #2차원

[[1]
 [2]
 [3]]
(3, 1)


In [26]:
#요소의 자료형

arr_f.dtype

dtype('int32')

In [27]:
#요소의 한개 크기

arr_f.itemsize


4

In [25]:
# 전체 요소의 개수

arr_f.size

3

In [28]:
# zeros(),eye(),ones()함수

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#arange() : array + range --> 배열의 범위
#np.arange(start,stop,step)

np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
print(np.arange(5))

[0 1 2 3 4]


In [33]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [34]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [35]:
# linspace() : 함수

np.linspace(0,10,10)
# 0부터 10(포함)까지  10개로 균등하게 나눠서 보여줘

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [37]:
np.linspace(1,10,5)
# 1부터 10(포함)까지 균등하게 5개로 나눠서 보여줘

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [40]:
# 2개의 배열 합치기

np.array([[1,2],[3,4]])

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [41]:
x + y 
# 같은 자리에 있는 원소가 합쳐진다

array([[ 6,  8],
       [10, 12]])

In [45]:
concat_0 = np.concatenate((x,y))

print(concat_0)
print(concat_0.shape)
# default : axis = 0 (행세열가)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [46]:
concat_1 = np.concatenate((x,y), axis=1)

print(concat_1)
print(concat_1.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [54]:
# vstack, hstack

# 1. vstack : v(Vertical 수직의) + stack(쌓아 올리다)

print(np.vstack((x,y)))
print()
print(concat_0)





[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [55]:
# 2. hstack : h(horizontal 수평의 )  + stack(쌓아 올리다)

print(np.hstack((x,y)))
print()
print(concat_1)


[[1 2 5 6]
 [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


### reshape(*****)

In [57]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
a = np.arange(12)

print(a.shape) # 결과값이 (N,) 이렇게 콤마 뒤에 없으면 행은 1개만 있다는 뜻이다

(12,)


In [60]:
# reshape(): 형태를 변경하겠다는 의미

# 1차원 ->> 2차원

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [61]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
dim_2 = a.reshape(3,4)  #2차원으로 바꿈
dim_2.shape

(3, 4)

In [63]:
a.reshape(3,-1)
# 형태를 행은 3개 만들고 싶은데 열은 그냥 전체 원소를 고려해서 끝(-1)에 맞춰줘(자동 맞추기)
# 자동으로 전체 원소 12개를 3개 행으로 나누어서 배열

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
temp = np.arange(11)

In [69]:
# temp.reshape(3,-1)
# 자동으로 맞출 때 원소 개수를 고려해서 진행해야함
# ex) temp = 11개 -> temp.shape(3,-1)
# temp가 11개인데 3행으로 자동으로 맞출려고 하면 원수의 개수가 맞지 않아서 오류 발생

In [70]:
# 배열 분할하기

np.arange(30).reshape(-1,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr1,arr2 = np.split(arr,[3],axis =1)

print(arr)
print()
print(arr2)

In [72]:
# 배열(array)에 새로운 축 추가하기

a = np.array([1,2,3,4,5,6])
print(a)
print()
print(a.shape) #1차원

[1 2 3 4 5 6]

(6,)


In [73]:
a[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6]])

In [74]:
a1 = a[np.newaxis, :]

print(a1.shape) #1*6 행렬(2차원)

(1, 6)


In [76]:
a2 = a[:, np.newaxis]
print(a2)
print()
print(a2.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

(6, 1)


In [81]:
# 인덱스

np.array([18,19,25,30,28])

array([18, 19, 25, 30, 28])

In [82]:
ages = np.array([18,19,25,30,28])

In [83]:
ages[2]

25

In [84]:
# 슬라이싱
print(ages[1:3])
print(ages[:-2])

[19 25]
[18 19 25]


In [85]:
#논리적 인덱싱

ages > 20

array([False, False,  True,  True,  True])

In [86]:
condition = (ages > 20)

In [87]:
ages[condition]

array([25, 30, 28])

In [88]:
ages[(ages>25)]

array([30, 28])

In [89]:
# 2차원 배열 인덱싱

np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
a =np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a[0])
print()
print(a[0][2])
print()
print(a[0,2])
print()
print(a[0,0])
print()
print(a[0,1])

[1 2 3]

3

3

1

2


In [94]:
a[0,0] = 12
print(a)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [97]:
a[0:2]
print(a[0:2])
print()
print(a[0:2].shape)

[[12  2  3]
 [ 4  5  6]]

(2, 3)


In [99]:
print(a)
print()
print(a[0:2,1:3]) # 행: 0~1 까지 열: 1~2까지 추출

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]

[[2 3]
 [5 6]]


In [100]:
a[::2,::2]

array([[12,  3],
       [ 7,  9]])

In [101]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[1,1],[1,1],[1,1]])

In [104]:
print(arr1)
print()
print(arr2)

[[1 2]
 [3 4]
 [5 6]]

[[1 1]
 [1 1]
 [1 1]]


In [106]:
result = arr1 + arr2

result


array([[2, 3],
       [4, 5],
       [6, 7]])

In [107]:
# list + list

a =[1,2,3,4]
b= [5,6,7,8]

a+b


[1, 2, 3, 4, 5, 6, 7, 8]

In [108]:
a.extend(b)

In [109]:
print(a)

[1, 2, 3, 4, 5, 6, 7, 8]


In [110]:
#브로드 캐스팅

np.array([1,2,3])  # (3,) 1차원


array([1, 2, 3])

In [111]:
miles = np.array([1,2,3])

miles + 1.6

array([2.6, 3.6, 4.6])

In [112]:
miles[0]  * 

SyntaxError: invalid syntax (2586777699.py, line 1)

In [114]:
#리스트는 될까?

# [1,2,3] * 1.6

# 결론 -> 안된다

# TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
# 넘파이 곱셈

In [115]:
arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[1,1],[1,1],[1,1]])


In [116]:
result = arr1 *arr2

In [118]:
result

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
# 내적(dot product) : 행렬 곱
# 입력 행렬 열@  출력 되는 행이 같아야 함
# ex) (x,3) @ (3,y) -->> (x , y)

In [121]:
scores = np.array([[90,85,70],[88,87,85],[95,60,80]])
scores

array([[90, 85, 70],
       [88, 87, 85],
       [95, 60, 80]])