In [1]:
# 배열 만들기

list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
import numpy as np

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
print(np.array([3,1.4,2,3,4.5]))

# 넘파이의 array는 단일 데이터 타입
# 정수 실수  -> 실수로 변경

[3.  1.4 2.  3.  4.5]


In [4]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
print(np.array([1,2,3,4]))

print(np.array([1,2,3,4],dtype=float))
arr =np.array([1,2,3,4],dtype=float)
print(arr)
print(arr.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
float64


In [8]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5),dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.random((2,2))
# 0~1 사이 균일 난수 생성
#(2,2) : size -> 튜플형태로 매개변수로 받아서 난수 생성

array([[8.51687480e-01, 4.39277738e-01],
       [1.52217183e-01, 1.07914989e-04]])

In [13]:
np.random.rand(2,2)
# 0~1 사이 균일 난수 생성
# 직접 차원(2,2) 인수 넣음

array([[0.72701976, 0.01778871],
       [0.43750989, 0.90715885]])

In [17]:
np.random.normal(0,1 ,(2,2)) 
# normal (평균, 표준편차, 매개변수 (튜플))
# 정규분포 형태, 매개변수를 튜플로 받아서 난수 생성

array([[ 0.14936587,  0.20485074],
       [ 0.27611201, -0.24859326]])

In [15]:
np.random.randn(2,2)
# 2 x 2 크기의 배열을 직접 생성

array([[-0.67007965,  1.18259314],
       [-1.11008964,  2.09415972]])

In [18]:
# indexing 과 slicing

np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [19]:
a = np.arange(7)

print(a[3])
print(a[-3])

3
4


In [26]:
np.random.randint(0,10,(2,2))
# 0에서 9(n-1)까지 숫자 범위에서
# 정수로 이어진 (2,2) 행렬 생성

array([[9, 9],
       [3, 2]])

In [25]:
# 배열의 기초

np.random.randint(10,size=(3,4))
# 10 : 최대값, 명시 안하면 최소값 0

array([[2, 5, 8, 7],
       [5, 0, 3, 0],
       [8, 4, 4, 2]])

In [27]:
x =np.random.randint(10,size=(3,4))

print(x.ndim)
print(x.shape)

2
(3, 4)


In [20]:
a[0] = 10

print(a)

[10  1  2  3  4  5  6]


In [24]:
#slicing

print(a)
print('-'*10)
print(a[1:4])
print('-'*10)
print(a[1:])
print('-'*10)
print(a[::2])   # 2칸씩 띄워서
print('-'*10)
print(a[::-1])  # 역순으로 출력(***)

[10  1  2  3  4  5  6]
----------
[1 2 3]
----------
[1 2 3 4 5 6]
----------
[10  2  4  6]
----------
[ 6  5  4  3  2  1 10]


In [33]:
# reshape(형태 변경)(***)

x = np.arange(8)

print(x)
print('-'*10)

print(x.shape) # 1차원 (8개 원소)
print('-'*10)

x2= x.reshape((2,4)) # 2차원 (2,4)행렬로 변환
print(x2)
print(x2.shape)

[0 1 2 3 4 5 6 7]
----------
(8,)
----------
[[0 1 2 3]
 [4 5 6 7]]
(2, 4)


In [35]:
# 이어 붙이고 나누기 작업

# 이어 붙이기 -> concatenate : array 이어서 붙임
x1 = np.array([0,1,2])
x2 = np.array([3,4,5])

print(x1)
print()
print(x2)
print()
print(np.concatenate([x1,x2]))


[0 1 2]

[3 4 5]

[0 1 2 3 4 5]


In [52]:
# concatenate -> axis 축 기준으로 이어 붙이기

m =np.arange(4).reshape(2,2)
print(m)
print()
print(np.concatenate([m,m], axis = 0)) # axis를 안적으면 기본 값 axis = 0 으로 인식 --> 세로 (행을 기준으로 넣는다는 뜻)
print()
print(np.concatenate([m,m],axis=1)) # axis = 1 -> 가로 (열을 기준으로 넣는다는 뜻)

[[0 1]
 [2 3]]

[[0 1]
 [2 3]
 [0 1]
 [2 3]]

[[0 1 0 1]
 [2 3 2 3]]


In [45]:
np.arange(16).reshape(4,4)

m =np.arange(16).reshape(4,4)
print(m)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [46]:
print(np.split(m,[3],axis=0))
# m 의 3열 기준으로  axis = 0 나눈다

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [49]:
m1, m2 =np.split(m,[3],axis=0)

print(m1)
print()
print(m2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]]


In [47]:
print(np.split(m,[3],axis=1))


[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [48]:
m3, m4 = np.split(m,[3],axis=1)

print(m3)
print()
print(m4)


[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]

[[ 3]
 [ 7]
 [11]
 [15]]


넘파이 연산

In [55]:
# array 의 모든 원소에 5를 더하는 함수 생성

def 더하기_5(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
      output[i] =values[i] + 5
    return output

values = np.random.randint(1,10, size =5)

print(values)
print()
print(더하기_5(values))

[6 6 8 2 1]

[11. 11. 13.  7.  6.]


In [56]:
# loop vs numpy

big_arr = np.random.randint(1,10, size =100000)

더하기_5(big_arr)

array([ 7., 13.,  9., ..., 12., 11., 10.])

In [57]:
big_arr + 5 # brodacastin 되어 계산 --> 훨씬 빠르다

array([ 7, 13,  9, ..., 12, 11, 10])

In [50]:
np.empty(5)
# 5개의 원소를 가진 1차원 배열 생성
# (초기화는 되어 있지 않음)
# 여기에 출력되는 값은 메모리에 이미 존재한 임의의 값으로 배열을 채움

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [58]:
# 기본 연산

np.arange(4)

array([0, 1, 2, 3])

In [59]:
x = np.arange(4)

print(x+5)
print(x-5)
print(x*5)
print(x/5)


[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]


In [62]:
# 행렬 간 연산

x = np.arange(4).reshape((2,2))
y = np.random.randint(10,size=(2,2))

print(x)
print()
print(y)
print()
print(x+y)
print()
print(x-y)

[[0 1]
 [2 3]]

[[5 0]
 [9 4]]

[[ 5  1]
 [11  7]]

[[-5  1]
 [-7 -1]]


In [63]:
# 브로드캐스팅(BrodaCasting)

print(x)
print()
print(x+5)

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]


In [64]:
# 집계함수

np.arange(8).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [65]:
x = np.arange(8).reshape((2,4))

print(np.sum(x))
print(np.min(x))
print(np.max(x))
print(np.mean(x))

28
0
7
3.5


In [67]:
# axis 사용, 집계하기

x = np.arange(8).reshape((2,4))
print(x)
print()
print(np.sum(x,axis=0))
print()
print(np.sum(x,axis=1))


[[0 1 2 3]
 [4 5 6 7]]

[ 4  6  8 10]

[ 6 22]


In [68]:
# 마스킹(masking) 연산 (조건 연산자 True/False)

np.arange(5)

array([0, 1, 2, 3, 4])

In [69]:
x = np.arange(5)

print(x<3)
print()
print(x>5)

[ True  True  True False False]

[False False False False False]


In [70]:
x[x<3]

array([0, 1, 2])

In [72]:
condition = (x<3)

x[condition]

array([0, 1, 2])